export default [{
	'name': 'Lemon',
	'codeName': 'lemon',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/lemon/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/5.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/6.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/7.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemon/9.jpg'
    }]
}, {
	'name': 'Elapse',
	'codeName': 'elapse',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/elapse/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/8.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/9.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/10.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/11.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/13.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/15.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/elapse/16.jpg'
	}]
},  {
	'name': 'Lemon',
	'codeName': 'afternoon',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/afternoon/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/5.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/6.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/7.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/8.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/9.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/10.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/11.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/12.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/13.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/14.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/15.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/16.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/17.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/18.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/19.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/20.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/21.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/22.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/23.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/24.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/25.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/26.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/27.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/28.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/29.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/30.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/31.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/32.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/33.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/34.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/35.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/36.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/37.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/38.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/39.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/40.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/41.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/afternoon/42.jpg'
    }]
}, {
	'name': 'Lemon',
	'codeName': 'lemoninspring',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/lemoninspring/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninspring/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninspring/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninspring/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninspring/5.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninspring/6.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninspring/7.jpg'
    }]
}, {
	'name': 'Lemon',
	'codeName': 'lemoninsummer',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/5.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/6.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lemoninsummer/7.jpg'
    }]
}, {
	'name': 'Lisa',
	'codeName': 'lisa',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/lisa/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/5.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/6.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/7.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/8.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/9.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/10.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/11.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/12.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/13.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/14.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/15.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/16.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/17.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/18.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/19.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/20.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/21.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/22.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/23.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/24.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/25.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisa/26.jpg'
    }]
}, {
	'name': 'Lisa',
	'codeName': 'lisaundressed',
	'gallery': [{
		'src': 'https://mephyo.github.io/gallery/lisaundressed/1.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/2.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/3.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/4.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/5.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/6.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/7.jpg'
    }, {
		'src': 'https://mephyo.github.io/gallery/lisaundressed/8.jpg'
    }]
}]