export default [{
	'name': 'Lemon',
	'codeName': 'lemon',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/lemon/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/7.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/8.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/9.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/10.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/11.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/12.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/13.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/14.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemon/15.jpg'
    }]
}, {
	'name': 'Elapse',
	'codeName': 'elapse',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/elapse/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/7.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/8.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/9.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/10.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/11.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/12.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/13.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/14.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/15.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/elapse/16.jpg'
	}]
}, {
	'name': 'Irene',
	'codeName': 'irene',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/irene/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/7.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/8.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/9.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/10.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/11.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/12.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/13.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/14.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/15.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/irene/16.jpg'
    }]
}, {
	'name': 'Lemon In Spring',
	'codeName': 'lemoninspring',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninspring/7.jpg'
    }]
}, {
	'name': 'Lemon In Summer',
	'codeName': 'lemoninsummer',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lemoninsummer/7.jpg'
    }]
}, {
	'name': 'Lisa',
	'codeName': 'lisa',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/lisa/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/7.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/8.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/9.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/10.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/11.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/12.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/13.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/14.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/15.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/16.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/17.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/18.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/19.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/20.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/21.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/22.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/23.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/24.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/25.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa/26.jpg'
    }]
}, {
	'name': 'Lisa~',
	'codeName': 'lisa~',
	'gallery': [{
		'src': 'http://mpy.eu5.org/gallery/lisa~/1.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/2.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/3.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/4.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/5.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/6.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/7.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/8.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/9.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/10.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/11.jpg'
    }, {
		'src': 'http://mpy.eu5.org/gallery/lisa~/12.jpg'
    }]
}, {
	'name': 'Afternoon',
	'codeName': 'afternoon',
	'gallery': [{
		'src': 'http://s6.postimg.org/m3j26f7b5/_MPY1272.jpg'
    }, {
		'src': 'http://s6.postimg.org/6w32m2fgh/_MPY1278.jpg'
    }, {
		'src': 'http://s6.postimg.org/vdv69yi0x/_MPY1305.jpg'
    }, {
		'src': 'http://s6.postimg.org/lulhghuip/_MPY1310.jpg'
    }, {
		'src': 'http://s6.postimg.org/4il4v211d/_MPY1312.jpg'
    }, {
		'src': 'http://s6.postimg.org/ze2bm78ht/_MPY1324.jpg'
    }, {
		'src': 'http://s6.postimg.org/w8hpvzpvl/_MPY1330.jpg'
    }, {
		'src': 'http://s6.postimg.org/5c2c1ewg1/_MPY1333.jpg'
    }, {
		'src': 'http://s6.postimg.org/62v276ytd/_MPY1356.jpg'
    }, {
		'src': 'http://s6.postimg.org/bsbari4zl/_MPY1360.jpg'
    }, {
		'src': 'http://s6.postimg.org/65exu12gx/_MPY1365.jpg'
    }, {
		'src': 'http://s6.postimg.org/ec6xllsjl/_MPY1366.jpg'
    }, {
		'src': 'http://s6.postimg.org/5v7faonup/_MPY1370.jpg'
    }, {
		'src': 'http://s6.postimg.org/vs13nari9/_MPY1374.jpg'
    }, {
		'src': 'http://s6.postimg.org/9hd8nbu81/_MPY1379.jpg'
    }, {
		'src': 'http://s6.postimg.org/t4g8qonup/_MPY1382.jpg'
    }, {
		'src': 'http://s6.postimg.org/649lecq0x/_MPY1388.jpg'
    }, {
		'src': 'http://s6.postimg.org/539cp891d/_MPY1392.jpg'
    }, {
		'src': 'http://s6.postimg.org/wrvzwqw1t/_MPY1399.jpg'
    }, {
		'src': 'http://s6.postimg.org/l41y276wx/_MPY1404.jpg'
    }, {
		'src': 'http://s6.postimg.org/av9gwdiv5/_MPY1408.jpg'
    }, {
		'src': 'http://s6.postimg.org/qi0q9qwn5/_MPY1412.jpg'
    }, {
		'src': 'http://s6.postimg.org/u2wlsz16p/_MPY1414.jpg'
    }, {
		'src': 'http://s6.postimg.org/7s8qt03wh/_MPY1439.jpg'
    }, {
		'src': 'http://s6.postimg.org/mcuf1ko8x/_MPY1442.jpg'
    }, {
		'src': 'http://s6.postimg.org/vynzhvfep/_MPY1448.jpg'
    }, {
		'src': 'http://s6.postimg.org/tvdka7flt/_MPY1451.jpg'
    }, {
		'src': 'http://s6.postimg.org/d8w014mo1/_MPY1452.jpg'
    }, {
		'src': 'http://s6.postimg.org/jnv0xstdt/_MPY1482.jpg'
    }, {
		'src': 'http://s6.postimg.org/p0jvbxha9/_MPY1483.jpg'
    }, {
		'src': 'http://s6.postimg.org/nzjmmt0ap/_MPY1495.jpg'
    }, {
		'src': 'http://s6.postimg.org/467iu3mwx/_MPY1498.jpg'
    }, {
		'src': 'http://s6.postimg.org/vi2rvfrnl/_MPY1504.jpg'
    }, {
		'src': 'http://s6.postimg.org/4ya6tar41/_MPY1505.jpg'
    }, {
		'src': 'http://s6.postimg.org/itd2piawx/_MPY1506.jpg'
    }, {
		'src': 'http://s6.postimg.org/mr0cewxq9/_MPY1508.jpg'
    }, {
		'src': 'http://s6.postimg.org/qbw7y529t/_MPY1520.jpg'
    }, {
		'src': 'http://s6.postimg.org/l1r96ui0x/_MPY1523.jpg'
    }, {
		'src': 'http://s6.postimg.org/dztbknef5/_MPY1525.jpg'
    }, {
		'src': 'http://s6.postimg.org/dobv7vxz5/_MPY1531.jpg'
    }, {
		'src': 'http://s6.postimg.org/dcuev4hj5/_MPY1532.jpg'
    }, {
		'src': 'http://s6.postimg.org/5ldowkddt/_MPY1534.jpg'
    }, {
		'src': 'http://s6.postimg.org/59w8jswxt/_MPY1535.jpg'
    }]
}]